version: "3.9"

services:
   redis:
      image: redis:alpine
      container_name: redis
   db:
      image: postgres
      volumes:
         - postgres_data:/var/lib/postgresql/data
      environment:
         - POSTGRES_DB=blog
         - POSTGRES_USER=blog_admin
         - POSTGRES_PASSWORD=qwerty12345
   web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/Blog
      ports:
         - "8000:8000"
      environment:
         - POSTGRES_DB=blog
         - POSTGRES_USER=blog_admin
         - POSTGRES_PASSWORD=qwerty12345
      depends_on:
         - db
      env_file:
         - .env
#   elasticsearch:
#      image: elasticsearch:8.0.1
#      container_name: elasticsearch
#      environment:
#         - discovery.type=single-node
#      ports:
#         - "9200:9200"
   celery:
      restart: always
      build:
         context: .
      command: celery -A Blog beat -l INFO
      volumes:
         - .:/django
      container_name: celery_beat
      depends_on:
         - db
         - redis
         - web

volumes:
   postgres_data: