version: "3.9"

services:
   redis:
      image: redis:alpine
      container_name: redis
   db:
      image: postgres
      volumes:
         - postgres_data:/var/lib/postgresql/data
      environment:
         - POSTGRES_DB=${DB_NAME}
         - POSTGRES_USER=${DB_USER}
         - POSTGRES_PASSWORD=${DB_PASSWORD}
   web:
      build: .
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
         - .:/Blog
      ports:
         - "8000:8000"
      environment:
         - POSTGRES_DB=${DB_NAME}
         - POSTGRES_USER=${DB_USER}
         - POSTGRES_PASSWORD=${DB_PASSWORD}
      depends_on:
         - db
      env_file:
         - .env
   celery:
      restart: always
      build: .
      command: bash -c "celery -A Blog worker -l INFO && celery -A Blog beat"
      volumes:
         - .:/django
      container_name: celery
      depends_on:
         - db
         - redis
         - web

volumes:
   postgres_data: